// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/drummonds/goEDMS"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/about": {
            "get": {
                "description": "Retrieve information about the application configuration, version, and database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get application information",
                "responses": {
                    "200": {
                        "description": "Application information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/clean": {
            "post": {
                "description": "Remove database entries for missing files and move orphaned files to ingress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Clean database",
                "responses": {
                    "200": {
                        "description": "Cleanup statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/document": {
            "delete": {
                "description": "Deletes a document or folder from the system, including database entry and physical file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Delete a file or folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ULID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "File path relative to document root",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Document Deleted\" or \"Folder Deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/document/move": {
            "patch": {
                "description": "Move one or more documents to a different folder in the document tree",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Move documents to a new folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target folder path",
                        "name": "folder",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Document ULID(s) to move",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/document/upload": {
            "post": {
                "description": "Upload a new document file to the ingress folder for processing",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Upload a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upload path (relative to ingress folder)",
                        "name": "path",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Document file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Path to uploaded file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/document/{id}": {
            "get": {
                "description": "Retrieve document details by ULID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Get a document by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ULID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Document details",
                        "schema": {
                            "$ref": "#/definitions/database.Document"
                        }
                    },
                    "404": {
                        "description": "Document not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/documents/filesystem": {
            "get": {
                "description": "Retrieve the complete document folder structure as a tree",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Get document filesystem tree",
                "responses": {
                    "200": {
                        "description": "Complete filesystem tree",
                        "schema": {
                            "$ref": "#/definitions/engine.fullFileSystem"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/documents/latest": {
            "get": {
                "description": "Retrieve the most recently ingested documents with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Documents"
                ],
                "summary": "Get latest documents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated documents with metadata",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/folder": {
            "post": {
                "description": "Create a new folder in the document filesystem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folders"
                ],
                "summary": "Create a new folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder name",
                        "name": "folder",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Parent path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Full folder path created",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/folder/{folder}": {
            "get": {
                "description": "Retrieve all documents in a specific folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folders"
                ],
                "summary": "Get folder contents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder name",
                        "name": "folder",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of documents in folder",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/database.Document"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ingest": {
            "post": {
                "description": "Manually trigger the document ingestion process to process files in the ingress folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Trigger document ingestion",
                "responses": {
                    "200": {
                        "description": "Ingestion started",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search all documents using PostgreSQL full-text search",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search documents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "term",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/engine.fileTreeStruct"
                            }
                        }
                    },
                    "204": {
                        "description": "No results found"
                    },
                    "404": {
                        "description": "Empty search term",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/search/reindex": {
            "post": {
                "description": "Rebuild the full-text search index for all documents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Reindex search documents",
                "responses": {
                    "200": {
                        "description": "Reindex successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Reindex failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wordcloud": {
            "get": {
                "description": "Retrieve the top N most frequent words from all documents for word cloud visualization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WordCloud"
                ],
                "summary": "Get word cloud data",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of words to return (default: 100, max: 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Word cloud data with words, metadata, and count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wordcloud/recalculate": {
            "post": {
                "description": "Trigger a full recalculation of word frequencies from all documents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WordCloud"
                ],
                "summary": "Recalculate word cloud",
                "responses": {
                    "200": {
                        "description": "Recalculation started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Document": {
            "type": "object",
            "properties": {
                "documentType": {
                    "description": "type of document (pdf, txt, etc)",
                    "type": "string"
                },
                "folder": {
                    "type": "string"
                },
                "fullText": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "ingressTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "description": "full path to the file",
                    "type": "string"
                },
                "stormID": {
                    "description": "ID field (kept as StormID for backward compatibility)",
                    "type": "integer"
                },
                "ulid": {
                    "description": "Have a smaller (than hash) id that can be used in URL's, hopefully speed things up",
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "engine.fileTreeStruct": {
            "type": "object",
            "properties": {
                "childrenIDs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fileURL": {
                    "type": "string"
                },
                "fullPath": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDir": {
                    "type": "boolean"
                },
                "modDate": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "openable": {
                    "type": "boolean"
                },
                "parentID": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "ulid": {
                    "type": "string"
                }
            }
        },
        "engine.fullFileSystem": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "fileSystem": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/engine.fileTreeStruct"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Document management operations",
            "name": "Documents"
        },
        {
            "description": "Full-text search and indexing operations",
            "name": "Search"
        },
        {
            "description": "Folder management operations",
            "name": "Folders"
        },
        {
            "description": "Administrative operations (ingestion, cleanup)",
            "name": "Admin"
        },
        {
            "description": "Word frequency analysis and word cloud generation",
            "name": "WordCloud"
        },
        {
            "description": "Service health check",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "goEDMS Backend API",
	Description:      "Electronic Document Management System API - Backend service for document storage, search, and management\nSupports document ingestion, full-text search, word cloud generation, and file system browsing",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
